# Generated by Django 5.0.1 on 2024-03-31 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0003_alter_question_section_alter_question_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_name', models.CharField(default='General', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(choices=[('General', 'General Knowledge'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('English', 'English'), ('Social Science', 'Social Science'), ('Software Engineering', 'Software Engineering'), ('Engineering Studies', 'Engineering Studies'), ('Languages', 'Languages')], default='General', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic_name',
            field=models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='eduprod.subtopic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic_name',
            field=models.ForeignKey(default='Introduction', on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='eduprod.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic_name',
            field=models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, to='eduprod.topic'),
            preserve_default=False,
        ),
    ]
